### ISSUE TITLE
Throw validation error on unknown flag

### ISSUE THREAD

**Issue by eysi09** [sywac/sywac#17]
Hi!

Is it possible to have the parser exit or throw an error when a given flag is invalid? Say I have something like:
```javascript
// cli.js
sywac
  .boolean("--dry-run", {
    desc: "Dry run",
  })
  .command("delete-all", {
    desc: "Deletes everything",
    run: (argv) => {
      if (argv["dry-run"]) {
        console.log("no harm done")
      } else {
        // wreak havoc
      }
    },
  })
  .help("-h, --help", { implicitCommand: false })
  .parseAndExit()
```
Now running this (notice the misspelled flag name):
```sh
# bad times
$ node cli.js delete-all --dyr-run
```
will indeed wreak havoc.

Currently I'm solving this by doing something like the following in the check function:
```javascript
const knownFlags = flatten(
  ctx.details.types
    .filter(t => t.datatype !== "command")
    .map(t => t.aliases),
)
const receivedFlags = Object.keys(argv)
```
and comparing the two arrays. But is there a more canonical way to solve this?

-Eythor.

EDIT: For completeness the entire cli would look like this:

```javascript
// Uses flatten and difference helper functions from lodash
sywac
  .boolean("--dry-run", {
    desc: "Dry run",
  })
  .command("delete-all", {
    desc: "Deletes everything",
    run: (argv) => {
      if (argv["dry-run"]) {
        console.log("no harm done")
      } else {
        console.log("wreak havoc")
      }
    },
  })
  .help("-h, --help", { implicitCommand: false })
  .check((argv, ctx) => {
    const knownFlags = flatten(
      ctx.details.types
        .filter(t => t.datatype !== "command")
        .map(t => t.aliases),
    )
    const receivedFlags = Object.keys(argv)
    if (difference(receivedFlags, knownFlags).length > 0) {
      ctx.cliMessage("Invalid flag")
    }
  })
  .parseAndExit()
```

**Comment by eysi09** [comment]
I guess I've kind of answered my own question but would be interested to hear if there's a more robust solution to this.

**Comment by nexdrew** [comment]
Hi 👋 thanks for reporting!

This is not something I usually do with my CLIs, but you have a good use-case here. There's no idiomatic way to do this with sywac right now, but I think it can be added to the api without much difficulty.

Give me some time to test out your particular scenario and work through a couple options, and I'll get back to you.

In the meantime, in order to properly apply your check at all command levels, you might need to define a common check function and use it in the command setup as well as at the top-level configuration. (Honestly though, it's been a while since I've looked at this codebase, so I need to get re-acquainted before I can offer you better advice.)

**Comment by eysi09** [comment]
Thanks!

For now I did something similar to what you suggested.

**Comment by nexdrew** [comment]
Well this has turned out to be quite a pain. 😃I apologize for not making this easier.

Assuming you're using a command-based CLI, I recommend using `.showHelpByDefault()`, which will ignore any invalid args (and print help text) unless a valid command (or top-level shortcut like `--version`) is given.

If we do so, then we don't need the custom check at top-level configuration, but we'll need it for each "runnable" command (each command that has a `run` handler).

Here's one example of how this might look:

```js
// issue17a.js
const sywac = require('sywac')
const { flatten, difference } = require('lodash')

function failOnInvalidFlag (argv, ctx) {
  const knownFlags = flatten(
    ctx.details.types
      .filter(t => t.datatype !== 'command')
      .map(t => t.aliases),
  )
  const receivedFlags = Object.keys(argv)
  const diff = difference(receivedFlags, knownFlags)
  if (diff.length > 0) {
    ctx.cliMessage(`Received invalid flag(s): ${diff.join(', ')}`)
  }
}

sywac
  .boolean('--dry-run', { desc: 'Dry run' })
  .command('delete-all', {
    desc: 'Deletes everything',
    setup: parser => {
      parser.boolean('--foo', { desc: 'Include foo' }).check(failOnInvalidFlag)
    },
    run: (argv) => {
      if (argv['dry-run']) {
        console.log('no harm done, foo:', argv.foo)
      } else {
        console.log('wreak havoc, foo:', argv.foo)
      }
    }
  })
  .help('-h, --help', { implicitCommand: false })
  .version('-v, --version', { implicitCommand: false })
  .showHelpByDefault()
  .outputSettings({ maxWidth: 50 })
  .parseAndExit()
```

```console
$ node issue17a.js 
Usage: issue17a <command> [options]

Commands:
  delete-all  Deletes everything

Options:
  --dry-run      Dry run                 [boolean]
  -h, --help     Show help               [boolean]
  -v, --version  Show version number     [boolean]
```

```console
$ node issue17a.js x -y
Usage: issue17a <command> [options]

Commands:
  delete-all  Deletes everything

Options:
  --dry-run      Dry run                 [boolean]
  -h, --help     Show help               [boolean]
  -v, --version  Show version number     [boolean]
```

```console
$ node issue17a.js delete-all
wreak havoc, foo: false
```

```console
$ node issue17a.js delete-all --foo
wreak havoc, foo: true
```

```console
$ node issue17a.js delete-all --foo --dry-run
no harm done, foo: true
```

```console
$ node issue17a.js delete-all --foo --dy-run
Usage: issue17a delete-all [options]

Options:
  --foo          Include foo             [boolean]
  --dry-run      Dry run                 [boolean]
  -h, --help     Show help               [boolean]
  -v, --version  Show version number     [boolean]

Received invalid flag(s): dy-run
```

```console
$ node issue17a.js delete-all --fo --dy-run
Usage: issue17a delete-all [options]

Options:
  --foo          Include foo             [boolean]
  --dry-run      Dry run                 [boolean]
  -h, --help     Show help               [boolean]
  -v, --version  Show version number     [boolean]

Received invalid flag(s): fo, dy-run
```

```console
$ node issue17a.js -v
1.0.0
```

I think this accomplishes the goal for your use-case.

If you would prefer not to use `.showHelpByDefault()`, then you would need to modify the `failOnInvalidFlag` function to be something like this (which relies on some sywac internals):

```js
function failOnInvalidFlag (argv, ctx, parser) {
  let willRunCommand = false
  const commands = parser.types.filter(type => type.datatype === 'command')
  for (let x = 0, match; x < commands.length; x++) {
    match = ctx.matchCommand(commands[x].api.parentName, commands[x].validAliases, commands[x].isDefault)
    if (match.explicit || match.implicit) {
      willRunCommand = true
      break
    }
  }
  if (willRunCommand) return

  const knownFlags = flatten(
    ctx.details.types
      .filter(t => t.datatype !== 'command')
      .map(t => t.aliases),
  )
  const receivedFlags = Object.keys(argv)
  const diff = difference(receivedFlags, knownFlags)
  if (diff.length > 0) {
    ctx.cliMessage(`Received invalid flag(s): ${diff.join(', ')}`)
  }
}
```

and then call it like this:

```js
.command('delete-all', {
  setup: parser => {
    parser.check((argv, ctx) => failOnInvalidFlag(argv, ctx, parser))
  }
})
```

Please let me know if you have any further questions or concerns. In the meantime, I'll be thinking about what we can add to sywac's api to make this a simple configuration option.

**Comment by nexdrew** [comment]
Also note that you can easily apply common custom functionality to all your commands by defining your own command type. Here's an example (code snippets):

```js
const TypeCommand = require('sywac/types/command')

function failOnInvalidFlag (argv, ctx) {
  // code from above
}

class StrictCommand extends TypeCommand {
  get setupHandler () {
    const fn = super.setupHandler
    return this.isDefault ? fn : parser => fn(parser.check(failOnInvalidFlag))
  }
}

sywac.registerFactory('commandType', opts => new StrictCommand(opts))

sywac
  .command('delete-all', {
    // do not have to call .check(failOnInvalidFlag) here
    setup: parser => parser.boolean('--foo', { desc: 'Include foo' })
  })
```

**Comment by eysi09** [comment]
Awesome! I'm using `showHelpByDefault` so the first example above works perfectly. I didn't think to add the `check` function to the nested `parser` object. Goes to show how flexible this library is. 

If anyone else should run into this, note that if you have nested commands with flags you'll need to add the `check` method to the deepest most `parser` object since a `check` on the parent command won't be aware of the flags on the sub-command and will fail if they're used.

As always, thanks for the quick and detailed response!

**Comment by nexdrew** [comment]
Cool, you're most welcome!

Would still be nice to have an api method to make this easy. I'll be giving it some thought and tinkering with a couple implementation options over the next week or so.

**Comment by trusktr** [comment]
I'm using `.showHelpByDefault()`, but when I try ` ./my-script.js --asdfasdf asdf` where `asdfasdf` it not a defined option, it doesn't show help, and runs my `.then` handler. Is it supposed to show help?

**Comment by nexdrew** [comment]
@trusktr The `.showHelpByDefault()` configuration is really meant for command-based CLIs - it is interpreted as "show help if no command is given". If your CLI doesn't use commands, then it won't help you much.

Currently sywac doesn't have configuration to fail on an unknown argument. You'd have to resort to some of the trickery above. Otherwise, you can set certain options as required, if your CLI has some.

**Comment by nexdrew** [comment]
@eysi09 @trusktr Just wanted to let you know that version 1.3.0 was published today, which now supports a `.strict()` mode configuration that will error when unknown flags or arguments are encountered during parsing.

If you're still using sywac, you might find it helpful/useful.

[See release notes here.](https://github.com/sywac/sywac/releases/tag/v1.3.0)

Thanks to @elliot-nelson for the implementation!
