### ISSUE TITLE
process exit

### ISSUE THREAD

**Issue by binarymist** [sywac/sywac#22]
How to stop the process exiting? Need to keep it running to accept SSE's to run an event listener.

**Comment by nexdrew** [comment]
Use the `.parse(args)` method rather than the `.parseAndExit(args)` method.

Here's a quote from the [docs](http://sywac.io/docs/async-parsing.html):

> This method is suitable for any application use. It treats each call as a stateless operation, accepting the input it needs and returning (as a Promise) the output result. It makes no assumptions about the application and therefore does not call any methods like console.log() or process.exit(). Rather, any potential output content (like help text) or error status (like an exit code) is reported in the result.

Both methods are asynchronous (returning a `Promise`), but `.parse(args)` resolves to a "result" object (that wraps the parsed `argv`) whereas `.parseAndExit(args)` resolves to the `argv` object directly.

**Comment by binarymist** [comment]
Yeah, I tried that.
