### ISSUE TITLE
trying to set a default on required parm

### ISSUE THREAD

**Issue by davidkjackson54** [sywac/sywac#29]
I am trying to set a default on a required parm and have the following coded
![image](https://user-images.githubusercontent.com/46171060/51954815-7e55f400-23f6-11e9-875b-de21f7d460fe.png)

When i display the command I see this:
![image](https://user-images.githubusercontent.com/46171060/51954738-3f27a300-23f6-11e9-823f-d95d63309712.png)

no default is assigned nor is the default (*)  displayed .  
I must be doing something wrong but nothing jumps out at me.

**Comment by nexdrew** [comment]
You have to remember that the object you're exporting represents the _command_, not its params, which means your sample code is attempting to assign a default value to the command itself, which doesn't make sense.

To more fully configure the params (positionals) for the command, use the `params` property (array of objects) instead of `paramsDesc` (array of strings).

Note that, [as stated in the docs](http://sywac.io/docs/sync-config.html#command), `paramsDesc` is just a shortcut to use when the only thing you need to configure in `params` would be a description.

> `paramsDescription` or `paramsDesc`: string or array of strings, shortcut to add description for positional args without defining `params`

Thus the following are equivalent:

```js
paramsDesc: ['Some description']
```

```js
params: [{ desc: 'Some description' }]
```

With that being said, we can fix your sample code by replacing `paramsDesc` with `params` and applying the `defaultValue` to the param configuration object.

Note that it doesn't really make sense to say a param is required when providing a default value, because you want the default value to be used when the argument is not given instead of requiring the user to provide the value.

Here are a couple ways of accomplishing this.

The first one changes the way the positional is declared in the `flags` DSL string, to remove the implicit requirement by using `[]` instead of `<>`:

```js
module.exports = {
  flags: 'pkglist [-p|--pkg] [package]',
  desc: 'Package List.',
  params: [{
    desc: 'Package Name',
    defaultValue: '*'
  }],
  run: a => console.log(`list package ${a.package}`)
}
```

```console
$ ./issue29.js pkglist -h
Usage: issue29 pkglist [-p|--pkg] [package] [options]

Arguments:
  [-p|--pkg] [package]  Package Name  [string] [default: *]

Global Options:
  -h, --help  Show help                           [boolean]
```

```console
$ ./issue29.js pkglist
list package *
```

```console
$ ./issue29.js pkglist x
list package x
```

The second one keeps the `flags` DSL the way you have it (using `<>`) but explicitly marks the param as not required:

```js
module.exports = {
  flags: 'pkglist [-p|--pkg] <package>',
  desc: 'Package List.',
  params: [{
    desc: 'Package Name',
    required: false,
    defaultValue: '*'
  }],
  run: a => console.log(`list package ${a.package}`)
}
```

```console
$ ./issue29.js pkglist -h
Usage: issue29 pkglist [-p|--pkg] <package> [options]

Arguments:
  [-p|--pkg] <package>  Package Name  [string] [default: *]

Global Options:
  -h, --help  Show help                           [boolean]
```

```console
$ ./issue29.js pkglist
list package *
```

```console
$ ./issue29.js pkglist x
list package x
```

**Comment by davidkjackson54** [comment]
Thanks for clarifying this. Really appreciate the help.
