### ISSUE TITLE
Is pkg actively maintained

### ISSUE THREAD

**Issue by LeonAlvarez** [sywac/sywac#34]
I just found this package want to use it, but I wonder if its actively maintained as the last update is 1 year ago. And docs still under construction.

**Comment by nexdrew** [comment]
Hi @LeonAlvarez!

Yes, this package is still maintained, I just haven't had time to update the tests since mjs modules are now a thing in Node, which is blocking dev dependency updates.

I also haven't been able to recruit any contributors, but this package is being used by several CLIs, including tools from Ghost, and I still plan to maintain it.

Let me know if you have any particular questions about how to use it.

**Comment by nexdrew** [comment]
Was finally able to give sywac a little love:

- Fixed the CI build on Node 12
- Upgraded dependencies (which are for testing only - sywac has no production dependencies) and closed out old Greenkeeper PRs
- Published the v1.2.2 release, since some minimal code changes were required for Node 12 and standard 13, which you can read about here: https://github.com/sywac/sywac/releases/tag/v1.2.2

The docs still need work, but please know that this project is still alive and kicking!

Thanks for asking about this and for giving sywac a try. I'm gonna close this issue, but we can reopen if you have any further questions.
