### ISSUE TITLE
Required positionals unless flag specified?

### ISSUE THREAD

**Issue by elliot-nelson** [sywac/sywac#42]
The interface I'd like for this command is that it requires all its arguments, unless you specify the optional --interactive flag, in which case you should specify none of them.

```
foo <a> <b> <c>
foo -i/--interactive
```

I'm guessing the best way here is to just set up 3 positional arguments and the flag all as optional and do my own validation inside my own method, but then override the entire usage text?  Opening issue in case there is a better way I'm missing.

**Comment by elliot-nelson** [comment]
After struggling with this for a while, I think I've come up with the best solution, which is:

1. In your DSL, use `<blah>`, that's what the user will see.
2. In a params block, override `required` to `false`.
3. Add a `check` handler, and mimic the errors that would sywac would normally display.

An example:

```
const bakeImage = {
  aliases: 'bake-image <instance-id> <image-name>',
  params: [
    { required: false, desc: 'Instance to use as the new image' },
    { required: false, desc: 'Name to assign to the new image' },
  ],
  setup: sywac => {
    sywac.boolean('-i, --interactive', {
      desc: 'Use interactive mode'
    });
    sywac.check((argv, context) => {
      if (!argv.interactive && !argv['instance-id'])
        return context.cliMessage('Missing required argument: instance-id');

      if (!argv.interactive && !argv['image-name'])
        return context.cliMessage('Missing required argument: image-name');
    });
  },
  run: argv => { /* etc */ }
};

sywac
  .command(bakeImage)
  .help('-h, --help')
  .showHelpByDefault()
  .parseAndExit();
```

This will give you the functionality I wanted (_either_ use `-i`, _or_ specify all arguments).  Sywac will not say the word "required" in the right-hand floater for the positional arguments, but they still look required due to convention, so I'm pretty pleased with the result!

**Comment by nexdrew** [comment]
Sorry, just now seeing this. I am AFK but what you came up with is probably what I'd recommend.

If you still want the positionals to display as required, you can also override the `hints` string in each param object.

The only other thing that comes to mind is the `ignore` property for your command (tell sywac to ignore certain positionals), but I don't think that's what you want here.

Next time I'm sitting at a computer I'll play a bit and see if I can come up with any other alternatives, but otherwise nice job! And thanks for sharing!
