### ISSUE TITLE
Option flags based on position in argv

### ISSUE THREAD

**Issue by elliot-nelson** [sywac/sywac#45]
I'm trying to port an old CLI interface to sywac and running into an edge case that's tricky.

This configuration tool has options that do different things depending on whether they are before or after commands.  For example:

```
slalom query -l 'retired' -i '10.11.*' update -l 'Retired'
```

There's a bunch of options (imagine `-l, --label`, `-n, --name`, etc.), but they mean "look for" in the first half of the CLI and "update" in the second half.  I've been playing with nested `command` blocks and setting up options, but it looks like there is no way to get at the value of the first `-l` (it is overwritten by the second globally).

Is this just a Sywac thing, where all "options" for the command line are considered global?  If so, I'll probably have to drop down to manually parsing args directly.

**Comment by nexdrew** [comment]
@elliot-nelson Hi - sorry I've been so AWOL on providing help with sywac!

My immediate thought would be to interpret `-l` as an array type (so it can hold multiple values) and then use the 1st element as the "look for" value and the 2nd element as the "update" value.

Otherwise, we might need to plug in a custom type for either the `-l` flag (to hold multiple values in a more suitable way) or for the command type (to override how "local" flags do or do not override "global" flags - which I'm not entirely sure is possible at the moment, but we could probably figure out something).

To plug in your own type, you can either use `sywac.registerFactory(nameString, factoryFunction)` or `sywac.custom(typeInstance)`.

**Comment by nexdrew** [comment]
@elliot-nelson Here's a super naive/minimalistic example of what I was describing:

```js
require('../sywac')
  .configure({ name: 'slalom' })
  .command('query', {
    setup: sywac => {
      sywac
        .array('-l')
        .string('-i')
        .command('update', {
          run: argv => {
            console.log(`look for ${argv.l[0]} in ${argv.i} and update to ${argv.l[1]}`)
          }
        })
    }
  })
  .showHelpByDefault()
  .parseAndExit()
```

```console
$ node issue45.js query -l 'retired' -i '10.11.*' update -l 'Retired'
look for retired in 10.11.* and update to Retired
```

Does something like that make sense for your use-case?

**Comment by elliot-nelson** [comment]
Thanks for the example!  That does make sense, but in reality I probably couldn't rely on it - because there are many fields that can be used as query, update, or both, the array would not always be 2 elements long.

For each field that is 1 element long, there's no way to tell whether the value is supposed to be a query or an update, because the params aren't actually attached to the command in any way.

(And maybe they shouldn't be - not every command line tool should be represented.  Imagine trying to represent a CLI like ImageMagick for example - totally different paradigm.)

**Comment by nexdrew** [comment]
Yeah. I'll admit that your example is not something I've seen in a CLI before, and sywac is probably not a good choice for that use-case at the moment.

Thanks for reporting!
