### ISSUE TITLE
Should certain stdout messages go to stderr?

### ISSUE THREAD

**Issue by elliot-nelson** [sywac/sywac#52]
I noticed this issue while experimenting with strict mode.  When writing small unix-style utilities, it's nice if only _expected_ output ends up on stdout, and other output ends up on stderr.

An example:

```js
// find-recent-project-files
#!/usr/bin/env node
require('sywac')
    .strict()
    .option('--client <string>', 'specify which client the project was for')
    .then(argv => {
        /* list the project files */
    });
```

```console
# touch recent project files for acme client
$ find-recent-project-files --clent acme | xargs -t touch
```

I think what I'd _want_ in this situation is for `find-recent-project-files` to immediately write its usage information and error message to `stderr`, where I can see it, and then write nothing (`""`) to `stdout`, which will be read and ignored by xargs.

Instead what happens is that I don't see the error message, except in little bits as spam from xargs attempting to "touch" a bunch of random words and punctuation.

(This is probably a breaking change, but overall might make sywac's behavior more predictable.)

**Comment by nexdrew** [comment]
This is a good point.

I think the best practice is to output to stdout _if and only if_ help text is requested (so I could pipe help content to `grep` or `less`); otherwise sywac should output (help content and error messages) to stderr when errors are encountered.

I agree that this would be a breaking change, but I'm all for it. Do you want to take a stab at this?

FYI, at some point I was also planning to replace all the `.then()` code with async/await, which I was going to reserve as another breaking change (since it would require Node versions 8+). I realize this would be a fairly significant refactor, but perhaps we could tackle both of these in preparation for a v2 release.

**Comment by nexdrew** [comment]
BTW I assume you're using `.parseAndExit()` since that's the only place sywac uses `console`; otherwise, when using `.parse()`, sywac doesn't output anything but leaves it up to the consumer to handle the `result.output` string as it chooses.

Regardless, it should be relatively easy to change the logic here to conditionally use `console.error` vs `console.log`: https://github.com/sywac/sywac/blob/14f5ef6d007d02caee25859e9ff3bcb83635aeed/api.js#L596-L599

**Comment by nexdrew** [comment]
@elliot-nelson I published the first v2 release candidate to npm as `sywac@2.0.0-rc1`. It should fix this problem. Give it a shot and let me know what you think.

See #54 for implementation details.
