### ISSUE TITLE
How to provide commands with additional data? 

### ISSUE THREAD

**Issue by vekat** [sywac/sywac#58]
I'm creating a chatbot and, with [yargs](https://github.com/yargs/yargs/blob/master/docs/api.md#parseargs-context-parsecallback), I was able to `.parse` a command and pass to it an arbitrary object which would be available, as part of the `argv` object, for further processing to all sub-commands in other directories.

Is there an equivalent for sywac?

**Comment by nexdrew** [comment]
It is possible in the current version of sywac to provide arbitrary data at runtime alongside a message that needs to be parsed, but it's not very straightforward.

Instead of just calling `.parse(msg)`, we need to first call `.registerFactory('_context', functionToInjectData)` for each message encountered at runtime.

Here's an example:

```js
// handle.js
// first configure sywac as normal
const sywac = require('sywac')
  .command('log', {
    run: argv => console.log(argv)
  })

// second, define a custom Context class to allow us to
// inject data into argv at runtime
const Context = require('sywac/context')

class Injector extends Context {
  constructor (opts) {
    super(opts)
    this.argv.injected = opts.injectData
  }
}

// third, inject arbitrary data and parse message at runtime
async function handle (msg, data) {
  const result = sywac
    .registerFactory('_context', opts => new Injector({
      injectData: data,
      ...opts
    }))
    .parse(msg)
  return result
}

module.exports = handle
```

If I take this sample code and wire it up to a Node script (for ease of testing), I can pass both `msg` and `data` to sywac, where sywac will parse `msg` to run a command and inject `data` into the `argv` object that is exposed to each command (at any level):

```js
// cli.js
const handle = require('./handle')

// by way of example, pass first command line arg in a data object
// and pass all other args as msg
handle(process.argv.slice(3), { arbitrary: process.argv[2] })
```

Then testing this in a terminal, I expect `hello` to be the injected data and `log` to be parsed and execute the command (the command is what's logging `argv` to stdout):

```console
$ node cli.js hello log
{ injected: { arbitrary: 'hello' }, _: [] }
```

I do not consider this an ideal solution, but hopefully it's a viable workaround for the time being. (I _think_ it's safe for concurrent parsing, assuming each thread/process loads its own instance of sywac, which is typical.)

We're currently in the process of preparing sywac v2 (bumping the major version b/c Node 8+ will now be required), so now would be a good time for us to add support for passing additional arbitrary `argv` data  to commands, possibly via a second argument to `.parse()`, like yargs. But before we add this, I'd like to understand your use-case better. Will you describe it for me please?

**Comment by vekat** [comment]
Thanks for the quick reply, nexdrew. I was suspecting I'd have to subclass your context class and now I understand it much better. I agree though, it does feel a little more complicated than expected to be considered an ideal solution.

> But before we add this, I'd like to understand your use-case better. Will you describe it for me please?

Yes, I can describe it:
Basically, there's a single point in my application where I start up a connection with an external API that allows me to talk with my users. This connection gives me an API client object and, once the connection is confirmed, I can be notified of message exchanges (which I'd like to treat as potential command requests) between the bot and users.

I'm trying to use sywac (previously tried yargs) to build a CLI-like interface for the bot. However, the context of each new message is given as a new object at runtime, and if I want to implement an entire command's business logic within sywac's command class, I'd need the contextual information from the particular message that invoked the it to be accessed by the command (e.g. Who was user? Are they a regular user? Should this user be able to invoke this administration commands? etc).

I hope this has explained my use case. I'm very interested in sywac because I quickly realised yargs was not ready to deal with potentially multiple concurrent messages (multiple invocations of the parse command, each having their own context) and Promise resolution. It seems that documentation is the main thing lacking in sywac, and I hope to help with that as I figure out how it works.

**Comment by nexdrew** [comment]
@vekat Thank you for describing that, makes perfect sense. I'd like to support this use-case. Do you think a 2nd argument to `.parse()` that gets attached to `argv` is good enough? Is there anything that would be more ideal?

**Comment by vekat** [comment]
I think that would be good enough. Maybe a *more ideal* version of it would just to attach the extra data to the `context` itself, assuming the context object represents exactly what its name suggest, and is unique for each new parse request. It seems that most functions that get access to `argv` can also access `context`.

**Comment by nexdrew** [comment]
@vekat Thanks for your feedback. I agree that it would probably be better to attach the data directly to the `context` instead of muddying up the `argv` object.

Concerning this:

> assuming the context object represents exactly what its name suggest, and is unique for each new parse request

Yes, this is exactly how context works, each call to `.parse()` uses a unique context instance that is separate and distinct from any other call.

I plan on writing up a PR to address this sometime this week. Thanks for opening this issue and for your valuable input!
